---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: sshd_Debian_status.yml
  when: ansible_os_family == 'Debian'

- include: sshd_RedHat_status.yml
  when: ansible_os_family == 'RedHat'

- name: ensure ed25519 host key is present
  command: ssh-keygen -q -t ed25519 -N "" -f ssh_host_ed25519_key
  args:
    chdir: /etc/ssh
    creates: /etc/ssh/ssh_host_ed25519_key
  when: openssh_version.stdout | version_compare('6.5', '>=')

- name: determine if ed25519 host key exists
  stat:
    path: /etc/ssh/ssh_host_ed25519_key
  register: ed25519_key

- name: ensure openssh config is latest
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd

- name: ensure sftp chroot group is present
  group:
    name: "{{ sshd_sftp_chroot_group }}"
  when: sshd_sftp_chroot == 'yes'
