- name: ensure openssh-server is present
  yum:
    name: openssh-server
    state: latest
  notify: restart sshd

- name: register openssh-server version
  shell: 'yum info openssh-server | grep "^Version" | sed -re "s/^.*: ([0-9]+\.[0-9]+).*/\1/"'
  register: openssh_version